---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hijabsya/public_html/afnitafitri.online
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp presensi.sql $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R bukti $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
